### ISSUE TITLE
Fix AttributeError in bot detector scraper

### ISSUE THREAD

**Issue by extreme4all** [Bot-detector/bot-detector-scraper#42]
```py
2023-11-27 18:48:05,970 - __main__ - scrape_data - ERROR - {'name': 'f7025336', 'error_type': 'AttributeError', 'error': AttributeError("'int' object has no attribute 'total'"), 'error_count': 0, 'player_name': 'raymond whee'}
2023-11-27 18:48:05,970 - __main__ - scrape_data - ERROR - 'int' object has no attribute 'total',
Traceback (most recent call last):
  File "/project/src/main_v2.py", line 257, in <module>
    loop = asyncio.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/project/src/main_v2.py", line 120, in scrape_data
    player, hiscore = await scraper.lookup_hiscores(player, session)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/src/modules/scraper.py", line 58, in lookup_hiscores
    highscore = await self.highscore_api.lookup_hiscores(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/src/modules/api/highscore_api.py", line 37, in lookup_hiscores
    async with session.get(url, proxy=self.proxy) as response:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1167, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 473, in _request
    tm = TimeoutHandle(self._loop, real_timeout.total)
                                   ^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'total'


```

**Comment by extreme4all** [comment]
https://github.com/Bot-detector/bot-detector-scraper/commit/242eee50ec13cd5e9678245a7d8cbdf9eb30d294
